name: WarningPlugin
version: 1.0
main: com.ngc0202.warningplugin.WarningPlugin
author: ngc0202
commands:
    warnen:
        description: Warnt ein Spieler
        usage: /warnen <spieler/"mindern"> <grund/Spieler> [Zahl]
        permission: warningplugin.warnen
        permission-message: Sie haben nicht die Erlaubnis, das zu tun.
        permission-message-2: Zugriff verweigert!
        
    warnungen:
        description: Zeigt an, wie viele Warnungen jemand hat.
        usage: /warnungen <Spieler>
        permission: warningplugin.warnungen
        permission-message: Sie haben nicht die Erlaubnis, das zu tun.