name: WarningPlugin
version: 1.0
main: com.ngc0202.warningplugin.WarningPlugin
author: ngc0202
commands:
    warnen:
        description: Warns a player.
        usage: /warn <player/"remove"> <reason/player> [number]
        permission: warningplugin.warn
        permission-message: You don't have the permissions to do that!
        
    warnungen:
        description: Checks how many warnings a player has gotten.
        usage: /warns [player]